In [1]:
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
df = sns.load_dataset('anscombe')

In [9]:
df.groupby('dataset').agg(['mean', 'std']).transpose()

dataset         I        II       III        IV
x mean   9.000000  9.000000  9.000000  9.000000
  std    3.316625  3.316625  3.316625  3.316625
y mean   7.500909  7.500909  7.500000  7.500909
  std    2.031568  2.031657  2.030424  2.030579

In [22]:
df.query('dataset in ["I", "II"]').corr()

          x         y
x  1.000000  0.816329
y  0.816329  1.000000